import { mutation, query, internalMutation } from "./_generated/server";
import { v, ConvexError } from "convex/values";
import { paginationOptsValidator } from "convex/server";
import { getUserFromToken } from "./auth";

function projectOrderForPickingList(order: any) {
  return {
    _id: order._id,
    userId: order.userId,
    orderNumber: order.orderNumber,
    shopifyOrderId: order.shopifyOrderId,
    customerName: order.customerName,
    customerEmail: order.customerEmail,
    customerPhone: order.customerPhone,
    notes: order.notes,
    totalPrice: order.totalPrice,
    totalShipping: order.totalShipping,
    totalDiscounts: order.totalDiscounts,
    currency: order.currency,
    status: order.status,
    fulfillmentStatus: order.fulfillmentStatus,
    deliveryStatus: order.deliveryStatus,
    trackingNumber: order.trackingNumber,
    awbGeneratedAt: order.awbGeneratedAt,
    invoiceNumber: order.invoiceNumber,
    invoiceSeries: order.invoiceSeries,
    invoiceStatus: order.invoiceStatus,
    invoiceCreatedAt: order.invoiceCreatedAt,
    paymentMethod: order.paymentMethod,
    createdAt: order.createdAt,
    placedOn: order.placedOn,
    isWorked: order.isWorked,
    workedAt: order.workedAt,
    workedBy: order.workedBy,
    workedByName: order.workedByName,
    stockDeducted: order.stockDeducted,
    stockDeductedAt: order.stockDeductedAt,
    printedAwb: order.printedAwb,
    printedInvoice: order.printedInvoice,
    lastPrintedAt: order.lastPrintedAt,
    lastPrintedBy: order.lastPrintedBy,
    isReturned: order.isReturned,
    returnedAt: order.returnedAt,
    returnId: order.returnId,
    openPackageRequested: order.openPackageRequested,
    customerNote: order.customerNote,
    // Keep activity history for the existing modal, but drop other heavy nested fields.
    activityHistory: order.activityHistory,
    shippingAddress: order.shippingAddress
      ? {
          line1: order.shippingAddress.line1 || order.shippingAddress.address1,
          line2: order.shippingAddress.line2 || order.shippingAddress.address2,
          city: order.shippingAddress.city,
          state: order.shippingAddress.state || order.shippingAddress.province,
          postalCode:
            order.shippingAddress.postalCode ||
            order.shippingAddress.zipCode ||
            order.shippingAddress.zip,
          zip: order.shippingAddress.zip,
          zipCode: order.shippingAddress.zipCode,
          country: order.shippingAddress.country,
          countryCode: order.shippingAddress.countryCode,
          stateCode: order.shippingAddress.stateCode || order.shippingAddress.provinceCode,
        }
      : undefined,
    // Keep only item fields used by table/editing; drop tax lines/properties/other Shopify payload.
    items: Array.isArray(order.items)
      ? order.items.map((item: any) => ({
          name: item.name,
          quantity: item.quantity,
          sku: item.sku,
          price: item.price,
        }))
      : [],
  };
}

// ============================================
// DAILY PICKING LISTS (Auto-generated by date)
// ============================================

// Get orders grouped by date for picking
export const getDailyPickingLists = query({
  args: {
    token: v.string(),
    days: v.optional(v.number()), // How many days back to show
    shopDomain: v.optional(v.string()), // Filter by store
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }

    const daysBack = args.days ?? 30;
    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - daysBack);
    const cutoffDateStr = cutoffDate.toISOString().split("T")[0];

    // --- Optimized: Use indexed date range instead of reading ALL orders ---
    let orders;
    if (args.shopDomain) {
      orders = await ctx.db
        .query("shopifyOrders")
        .withIndex("by_userId_shopDomain_placedOn", (q) =>
          q.eq("userId", user._id)
            .eq("shopDomain", args.shopDomain!)
            .gte("placedOn", cutoffDateStr)
        )
        .collect();
    } else {
      orders = await ctx.db
        .query("shopifyOrders")
        .withIndex("by_userId_placedOn", (q) =>
          q.eq("userId", user._id).gte("placedOn", cutoffDateStr)
        )
        .collect();
    }

    // Group by date
    const ordersByDate = new Map<string, typeof orders>();

    for (const order of orders) {
      if (order.placedOn >= cutoffDateStr) {
        const dateOrders = ordersByDate.get(order.placedOn) ?? [];
        dateOrders.push(order);
        ordersByDate.set(order.placedOn, dateOrders);
      }
    }

    // Convert to array and sort by date descending
    const dailyLists = Array.from(ordersByDate.entries())
      .map(([date, dateOrders]) => {
        // Calculate stats for this date
        const totalRevenue = dateOrders.reduce((sum, o) => sum + o.totalPrice, 0);
        const withAwb = dateOrders.filter((o) => o.trackingNumber).length;
        const withInvoice = dateOrders.filter((o) => o.invoiceNumber).length;
        const fulfilled = dateOrders.filter(
          (o) => o.fulfillmentStatus === "fulfilled"
        ).length;

        // Format display date (e.g., "27.01")
        const [_year, month, day] = date.split("-");
        const displayDate = `${day}.${month}`;

        return {
          date,
          displayDate,
          orderCount: dateOrders.length,
          totalRevenue,
          stats: {
            total: dateOrders.length,
            withAwb,
            withInvoice,
            fulfilled,
            pending: dateOrders.length - fulfilled,
          },
        };
      })
      .sort((a, b) => b.date.localeCompare(a.date));

    return dailyLists;
  },
});

// Get orders for a specific date (picking list detail)
export const getOrdersByDate = query({
  args: {
    token: v.string(),
    date: v.string(), // "YYYY-MM-DD"
    shopDomain: v.optional(v.string()), // Filter by store
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }

    // Get orders for this date
    let orders = await ctx.db
      .query("shopifyOrders")
      .withIndex("by_userId_placedOn", (q) =>
        q.eq("userId", user._id).eq("placedOn", args.date)
      )
      .collect();

    // Filter by store if specified
    if (args.shopDomain) {
      orders = orders.filter((o) => o.shopDomain === args.shopDomain);
    }

    // Work status is now denormalized directly on the order (isWorked, workedAt, etc.)

    // Calculate stats
    const stats = {
      totalOrders: orders.length,
      totalRevenue: orders.reduce((sum, o) => sum + o.totalPrice, 0),
      ordersWorked: orders.filter((o) => o.isWorked).length,
      awbsGenerated: orders.filter((o) => o.trackingNumber).length,
      invoicesCreated: orders.filter((o) => o.invoiceNumber).length,
    };

    // Aggregate products across all orders
    const productMap = new Map<
      string,
      { sku: string; name: string; quantity: number }
    >();
    orders.forEach((order) => {
      order?.items?.forEach((item: { sku?: string; name?: string; quantity?: number }) => {
        const key = item.sku || item.name || "unknown";
        const existing = productMap.get(key);
        if (existing) {
          existing.quantity += item.quantity || 1;
        } else {
          productMap.set(key, {
            sku: item.sku || "",
            name: item.name || "",
            quantity: item.quantity || 1,
          });
        }
      });
    });

    // Format display date
    const [_year, month, day] = args.date.split("-");
    const dateObj = new Date(args.date);
    const displayDate = dateObj.toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    return {
      date: args.date,
      displayDate,
      shortDate: `${day}.${month}`,
      orders,
      stats,
      aggregatedProducts: Array.from(productMap.values()).sort(
        (a, b) => b.quantity - a.quantity
      ),
    };
  },
});

// ============================================
// LEGACY MANUAL PICKING LISTS
// ============================================

export const list = query({
  args: {
    token: v.string(),
    status: v.optional(v.string()),
    shopDomain: v.optional(v.string()), // Filter by store
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }
    
    let pickingLists;
    if (args.shopDomain) {
      pickingLists = await ctx.db
        .query("pickingLists")
        .withIndex("by_userId_shopDomain", q => q.eq("userId", user._id).eq("shopDomain", args.shopDomain))
        .order("desc")
        .collect();
    } else {
      pickingLists = await ctx.db
        .query("pickingLists")
        .withIndex("by_userId", q => q.eq("userId", user._id))
        .order("desc")
        .collect();
    }
    
    if (args.status) {
      pickingLists = pickingLists.filter(pl => pl.status === args.status);
    }
    
    // Get order counts for each list
    const listsWithCounts = await Promise.all(
      pickingLists.map(async (list) => {
        const items = await ctx.db
          .query("pickingListItems")
          .withIndex("by_pickingListId", q => q.eq("pickingListId", list._id))
          .collect();
        
        return {
          ...list,
          orderCount: items.length,
        };
      })
    );
    
    return listsWithCounts;
  },
});

export const getById = query({
  args: {
    token: v.string(),
    id: v.id("pickingLists"),
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }
    
    const list = await ctx.db.get(args.id);
    if (!list || list.userId !== user._id) {
      return null;
    }
    
    return list;
  },
});

export const getWithOrders = query({
  args: {
    token: v.string(),
    id: v.id("pickingLists"),
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }
    
    const list = await ctx.db.get(args.id);
    if (!list || list.userId !== user._id) {
      return null;
    }
    
    // Get all items in this list
    const listItems = await ctx.db
      .query("pickingListItems")
      .withIndex("by_pickingListId", q => q.eq("pickingListId", args.id))
      .collect();
    
    // Get orders for each item
    const orderPromises = listItems.map((item) => ctx.db.get(item.orderId));
    const rawOrders = await Promise.all(orderPromises);

    const orders = rawOrders.map((order, i) => {
      if (!order) return null;
      
      // Work status is now denormalized directly on the order
      return {
        ...projectOrderForPickingList(order),
        pickingListItemId: listItems[i]._id,
        // isWorked, workedAt, workedBy, workedByName are already on the order
      };
    });
    
    // Filter out null orders
    const validOrders = orders.filter(o => o !== null);
    
    // Calculate stats
    const stats = {
      totalOrders: validOrders.length,
      totalRevenue: validOrders.reduce((sum, o) => sum + (o?.totalPrice || 0), 0),
      ordersWorked: validOrders.filter(o => o?.isWorked).length,
      awbsGenerated: validOrders.filter(o => o?.trackingNumber).length,
      invoicesCreated: validOrders.filter(o => o?.invoiceNumber).length,
    };
    
    // Aggregate products
    const productMap = new Map<string, { sku: string; name: string; quantity: number }>();
    validOrders.forEach(order => {
      order?.items?.forEach((item: any) => {
        const key = item.sku || item.name;
        const existing = productMap.get(key);
        if (existing) {
          existing.quantity += item.quantity || 1;
        } else {
          productMap.set(key, {
            sku: item.sku || "",
            name: item.name || "",
            quantity: item.quantity || 1,
          });
        }
      });
    });
    
    return {
      ...list,
      orders: validOrders,
      stats,
      aggregatedProducts: Array.from(productMap.values()),
    };
  },
});

export const getOrderIds = query({
  args: {
    token: v.string(),
    id: v.id("pickingLists"),
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }

    const list = await ctx.db.get(args.id);
    if (!list || list.userId !== user._id) {
      return [];
    }

    const listItems = await ctx.db
      .query("pickingListItems")
      .withIndex("by_pickingListId", (q) => q.eq("pickingListId", args.id))
      .collect();

    return listItems.map((item) => item.orderId);
  },
});

export const listOrdersPaginated = query({
  args: {
    token: v.string(),
    id: v.id("pickingLists"),
    paginationOpts: paginationOptsValidator,
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }

    const list = await ctx.db.get(args.id);
    if (!list || list.userId !== user._id) {
      return {
        page: [],
        isDone: true,
        continueCursor: "",
      };
    }

    const result = await ctx.db
      .query("pickingListItems")
      .withIndex("by_pickingListId", (q) => q.eq("pickingListId", args.id))
      .order("desc")
      .paginate(args.paginationOpts);

    const orderPromises = result.page.map((item) => ctx.db.get(item.orderId));
    const rawOrders = await Promise.all(orderPromises);

    const page = result.page.map((item, i) => {
      const order = rawOrders[i];
      if (!order || order.userId !== user._id) return null;
      return {
        ...projectOrderForPickingList(order),
        pickingListItemId: item._id,
      };
    });

    return {
      ...result,
      page: page.filter((o) => o !== null),
    };
  },
});

export const create = mutation({
  args: {
    token: v.string(),
    name: v.string(),
    shopDomain: v.optional(v.string()), // Which store this list belongs to
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }
    
    const id = await ctx.db.insert("pickingLists", {
      userId: user._id,
      shopDomain: args.shopDomain,
      name: args.name,
      status: "pending",
      createdAt: Date.now(),
      updatedAt: Date.now(),
    });
    
    return id;
  },
});

// Get or create today's picking list
export const getOrCreateToday = mutation({
  args: {
    token: v.string(),
    shopDomain: v.optional(v.string()), // Which store
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }
    
    // Format today's date
    const today = new Date();
    const day = today.getDate().toString().padStart(2, "0");
    const month = (today.getMonth() + 1).toString().padStart(2, "0");
    const year = today.getFullYear();
    const todayName = `Picking List ${day}.${month}.${year}`;
    
    // Check if today's list already exists for this store
    let pickingLists;
    if (args.shopDomain) {
      pickingLists = await ctx.db
        .query("pickingLists")
        .withIndex("by_userId_shopDomain", q => q.eq("userId", user._id).eq("shopDomain", args.shopDomain))
        .collect();
    } else {
      pickingLists = await ctx.db
        .query("pickingLists")
        .withIndex("by_userId", q => q.eq("userId", user._id))
        .collect();
    }
    
    const existingToday = pickingLists.find(pl => pl.name === todayName);
    
    if (existingToday) {
      return { id: existingToday._id, name: existingToday.name, created: false };
    }
    
    // Create new picking list for today
    const id = await ctx.db.insert("pickingLists", {
      userId: user._id,
      shopDomain: args.shopDomain,
      name: todayName,
      status: "pending",
      createdAt: Date.now(),
      updatedAt: Date.now(),
    });
    
    return { id, name: todayName, created: true };
  },
});

// Add single order to picking list (with auto-create today option)
export const addSingleOrder = mutation({
  args: {
    token: v.string(),
    orderId: v.id("shopifyOrders"),
    pickingListId: v.optional(v.id("pickingLists")),
    useToday: v.optional(v.boolean()),
    shopDomain: v.optional(v.string()), // Which store (used when auto-creating today's list)
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }
    
    // Verify order belongs to user
    const order = await ctx.db.get(args.orderId);
    if (!order || order.userId !== user._id) {
      throw new ConvexError("Comanda nu a fost găsită.");
    }
    
    // Use the order's shopDomain if not explicitly provided
    const shopDomain = args.shopDomain || order.shopDomain;
    
    let pickingListId = args.pickingListId;
    let pickingListName = "";
    
    // If useToday, get or create today's list for this store
    if (args.useToday && !pickingListId) {
      const today = new Date();
      const day = today.getDate().toString().padStart(2, "0");
      const month = (today.getMonth() + 1).toString().padStart(2, "0");
      const year = today.getFullYear();
      const todayName = `Picking List ${day}.${month}.${year}`;
      
      // Find existing today's list for this store
      let pickingLists;
      if (shopDomain) {
        pickingLists = await ctx.db
          .query("pickingLists")
          .withIndex("by_userId_shopDomain", q => q.eq("userId", user._id).eq("shopDomain", shopDomain))
          .collect();
      } else {
        pickingLists = await ctx.db
          .query("pickingLists")
          .withIndex("by_userId", q => q.eq("userId", user._id))
          .collect();
      }
      
      const existingToday = pickingLists.find(pl => pl.name === todayName);
      
      if (existingToday) {
        pickingListId = existingToday._id;
        pickingListName = existingToday.name;
      } else {
        pickingListId = await ctx.db.insert("pickingLists", {
          userId: user._id,
          shopDomain,
          name: todayName,
          status: "pending",
          createdAt: Date.now(),
          updatedAt: Date.now(),
        });
        pickingListName = todayName;
      }
    }
    
    if (!pickingListId) {
      throw new ConvexError("Nu a fost specificat un picking list.");
    }
    
    // Verify picking list belongs to user
    const list = await ctx.db.get(pickingListId);
    if (!list || list.userId !== user._id) {
      throw new ConvexError("Lista de picking nu a fost găsită.");
    }
    pickingListName = pickingListName || list.name;
    
    // Check if already in list
    const existingItem = await ctx.db
      .query("pickingListItems")
      .withIndex("by_pickingListId", q => q.eq("pickingListId", pickingListId!))
      .filter(q => q.eq(q.field("orderId"), args.orderId))
      .first();
    
    if (existingItem) {
      return { success: true, alreadyExists: true, pickingListName };
    }
    
    // Add to list
    await ctx.db.insert("pickingListItems", {
      pickingListId,
      orderId: args.orderId,
      createdAt: Date.now(),
    });
    
    // Update list timestamp
    await ctx.db.patch(pickingListId, {
      updatedAt: Date.now(),
    });
    
    return { success: true, alreadyExists: false, pickingListName };
  },
});

export const addOrders = mutation({
  args: {
    token: v.string(),
    pickingListId: v.id("pickingLists"),
    orderIds: v.array(v.id("shopifyOrders")),
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }
    
    const list = await ctx.db.get(args.pickingListId);
    if (!list || list.userId !== user._id) {
      throw new ConvexError("Lista de picking nu a fost găsită.");
    }
    
    // Get existing items to avoid duplicates
    const existingItems = await ctx.db
      .query("pickingListItems")
      .withIndex("by_pickingListId", q => q.eq("pickingListId", args.pickingListId))
      .collect();
    
    const existingOrderIds = new Set(existingItems.map(i => i.orderId));
    
    // Add new orders
    let addedCount = 0;
    let skippedCount = 0;
    for (const orderId of args.orderIds) {
      if (!existingOrderIds.has(orderId)) {
        // Verify order belongs to user
        const order = await ctx.db.get(orderId);
        if (order && order.userId === user._id) {
          await ctx.db.insert("pickingListItems", {
            pickingListId: args.pickingListId,
            orderId,
            createdAt: Date.now(),
          });
          addedCount++;
        }
      } else {
        skippedCount++;
      }
    }
    
    // Update list timestamp
    await ctx.db.patch(args.pickingListId, {
      updatedAt: Date.now(),
    });
    
    return { addedCount, skippedCount, pickingListName: list.name };
  },
});

export const removeOrder = mutation({
  args: {
    token: v.string(),
    pickingListId: v.id("pickingLists"),
    orderId: v.id("shopifyOrders"),
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }
    
    const list = await ctx.db.get(args.pickingListId);
    if (!list || list.userId !== user._id) {
      throw new ConvexError("Lista de picking nu a fost găsită.");
    }
    
    // Find and delete the item
    const item = await ctx.db
      .query("pickingListItems")
      .withIndex("by_pickingListId", q => q.eq("pickingListId", args.pickingListId))
      .filter(q => q.eq(q.field("orderId"), args.orderId))
      .first();
    
    if (item) {
      await ctx.db.delete(item._id);
    }
    
    // Update list timestamp
    await ctx.db.patch(args.pickingListId, {
      updatedAt: Date.now(),
    });
    
    return { success: true };
  },
});

export const markOrderWorked = mutation({
  args: {
    token: v.string(),
    orderId: v.id("shopifyOrders"),
    pickingListId: v.optional(v.id("pickingLists")),
    worked: v.boolean(),
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }
    
    const order = await ctx.db.get(args.orderId);
    if (!order || order.userId !== user._id) {
      throw new ConvexError("Comanda nu a fost găsită.");
    }
    
    const existing = await ctx.db
      .query("orderWorkStatus")
      .withIndex("by_orderId", q => q.eq("orderId", args.orderId))
      .first();
    
    if (args.worked && !existing) {
      // Mark as worked
      await ctx.db.insert("orderWorkStatus", {
        orderId: args.orderId,
        pickingListId: args.pickingListId,
        markedBy: user._id,
        markedAt: new Date().toISOString(),
        createdAt: Date.now(),
      });
      
      // Update picking list status if needed
      if (args.pickingListId) {
        const list = await ctx.db.get(args.pickingListId);
        if (list && list.status === "pending") {
          await ctx.db.patch(args.pickingListId, {
            status: "in_progress",
            updatedAt: Date.now(),
          });
        }
      }
    } else if (!args.worked && existing) {
      // Unmark as worked
      await ctx.db.delete(existing._id);
    }
    
    return { success: true };
  },
});

export const updateStatus = mutation({
  args: {
    token: v.string(),
    pickingListId: v.id("pickingLists"),
    status: v.string(),
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }
    
    const list = await ctx.db.get(args.pickingListId);
    if (!list || list.userId !== user._id) {
      throw new ConvexError("Lista de picking nu a fost găsită.");
    }
    
    await ctx.db.patch(args.pickingListId, {
      status: args.status,
      updatedAt: Date.now(),
    });
    
    return { success: true };
  },
});

export const remove = mutation({
  args: {
    token: v.string(),
    pickingListId: v.id("pickingLists"),
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }
    
    const list = await ctx.db.get(args.pickingListId);
    if (!list || list.userId !== user._id) {
      throw new ConvexError("Lista de picking nu a fost găsită.");
    }
    
    // Delete all items first
    const items = await ctx.db
      .query("pickingListItems")
      .withIndex("by_pickingListId", q => q.eq("pickingListId", args.pickingListId))
      .collect();
    
    for (const item of items) {
      await ctx.db.delete(item._id);
    }
    
    // Delete the list
    await ctx.db.delete(args.pickingListId);
    
    return { success: true };
  },
});

// Check if order is in any picking list
export const getOrderPickingList = query({
  args: {
    token: v.string(),
    orderId: v.id("shopifyOrders"),
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }
    
    const item = await ctx.db
      .query("pickingListItems")
      .withIndex("by_orderId", q => q.eq("orderId", args.orderId))
      .first();
    
    if (!item) return null;
    
    const list = await ctx.db.get(item.pickingListId);
    return list;
  },
});

// Get all order -> picking list mappings for the user (for efficient table display)
export const getAllOrderPickingListMappings = query({
  args: {
    token: v.string(),
    shopDomain: v.optional(v.string()), // Filter by store
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }
    
    // Get picking lists for this user, filtered by store if specified
    let pickingLists;
    if (args.shopDomain) {
      pickingLists = await ctx.db
        .query("pickingLists")
        .withIndex("by_userId_shopDomain", q => q.eq("userId", user._id).eq("shopDomain", args.shopDomain))
        .collect();
    } else {
      pickingLists = await ctx.db
        .query("pickingLists")
        .withIndex("by_userId", q => q.eq("userId", user._id))
        .collect();
    }
    
    // Create a map of pickingListId -> name
    const listNames = new Map(pickingLists.map(pl => [pl._id, pl.name]));
    
    // Get all picking list items for all lists
    const allMappings: { orderId: string; pickingListId: string; pickingListName: string }[] = [];
    
    for (const list of pickingLists) {
      const items = await ctx.db
        .query("pickingListItems")
        .withIndex("by_pickingListId", q => q.eq("pickingListId", list._id))
        .collect();
      
      for (const item of items) {
        allMappings.push({
          orderId: item.orderId,
          pickingListId: list._id,
          pickingListName: listNames.get(list._id) || "",
        });
      }
    }
    
    return allMappings;
  },
});

// Get order -> picking list mappings only for a specific set of orders
export const getOrderPickingListMappingsForOrders = query({
  args: {
    token: v.string(),
    orderIds: v.array(v.id("shopifyOrders")),
    shopDomain: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }

    if (args.orderIds.length === 0) {
      return [] as { orderId: string; pickingListId: string; pickingListName: string }[];
    }

    const listCache = new Map<string, { _id: string; name: string; shopDomain?: string } | null>();
    const mappings: { orderId: string; pickingListId: string; pickingListName: string }[] = [];

    for (const orderId of args.orderIds) {
      const items = await ctx.db
        .query("pickingListItems")
        .withIndex("by_orderId", (q) => q.eq("orderId", orderId))
        .collect();

      for (const item of items) {
        const cacheKey = item.pickingListId as string;
        let list = listCache.get(cacheKey);
        if (list === undefined) {
          const found = await ctx.db.get(item.pickingListId);
          if (!found || found.userId !== user._id) {
            list = null;
          } else {
            list = {
              _id: found._id,
              name: found.name,
              shopDomain: found.shopDomain,
            };
          }
          listCache.set(cacheKey, list);
        }

        if (!list) continue;
        if (args.shopDomain && list.shopDomain !== args.shopDomain) continue;

        mappings.push({
          orderId: item.orderId,
          pickingListId: list._id,
          pickingListName: list.name,
        });
      }
    }

    return mappings;
  },
});

// ============================================
// MIGRATION: Backfill shopDomain on existing picking lists
// ============================================

export const migrateBackfillShopDomain = mutation({
  args: {
    token: v.string(),
  },
  handler: async (ctx, args) => {
    const user = await getUserFromToken(ctx, args.token);
    if (!user) {
      throw new ConvexError("Sesiune expirată. Te rugăm să te autentifici din nou.");
    }

    // Get all picking lists for this user that have no shopDomain
    const allLists = await ctx.db
      .query("pickingLists")
      .withIndex("by_userId", q => q.eq("userId", user._id))
      .collect();

    const listsWithoutDomain = allLists.filter(pl => !pl.shopDomain);

    let updated = 0;
    let skipped = 0;
    let empty = 0;

    for (const list of listsWithoutDomain) {
      // Get the orders in this picking list
      const items = await ctx.db
        .query("pickingListItems")
        .withIndex("by_pickingListId", q => q.eq("pickingListId", list._id))
        .collect();

      if (items.length === 0) {
        // Empty list — try to assign based on user's stores (use first/primary)
        // We'll skip these for now; they'll show up when no store filter is active
        skipped++;
        continue;
      }

      // Look at the first order to determine the shopDomain
      const firstOrder = await ctx.db.get(items[0].orderId);
      if (firstOrder?.shopDomain) {
        await ctx.db.patch(list._id, {
          shopDomain: firstOrder.shopDomain,
          updatedAt: Date.now(),
        });
        updated++;
      } else {
        empty++;
      }
    }

    return {
      total: listsWithoutDomain.length,
      updated,
      skipped,
      noShopDomain: empty,
    };
  },
});

// ============================================
// CRON: Create today's picking list for all users
// ============================================

export const createDailyPickingListsCron = internalMutation({
  args: {},
  handler: async (ctx) => {
    // Get all users
    const users = await ctx.db.query("profiles").collect();
    
    // Format today's date
    const today = new Date();
    const day = today.getDate().toString().padStart(2, "0");
    const month = (today.getMonth() + 1).toString().padStart(2, "0");
    const year = today.getFullYear();
    const todayName = `Picking List ${day}.${month}.${year}`;
    
    let created = 0;
    let skipped = 0;
    
    for (const user of users) {
      // Check if today's list already exists for this user
      const existingLists = await ctx.db
        .query("pickingLists")
        .withIndex("by_userId", (q) => q.eq("userId", user._id))
        .collect();
      
      const existingToday = existingLists.find((pl) => pl.name === todayName);
      
      if (!existingToday) {
        // Create new picking list for today
        await ctx.db.insert("pickingLists", {
          userId: user._id,
          name: todayName,
          status: "pending",
          createdAt: Date.now(),
          updatedAt: Date.now(),
        });
        created++;
      } else {
        skipped++;
      }
    }
    
    console.log(`Daily picking lists cron: created ${created}, skipped ${skipped} (already existed)`);
    return { created, skipped };
  },
});